### PR TITLE
Simple refresh of Shape Sample to more recent KorGE features

### PR DESCRIPTION
**Pull request by emign**
very minor

### CODE REVIEW

**Comment by RezMike** [comment]
Hm, could we save both versions? The old one like more straightforward/thorough and the new one like more optimal and recommended?

**Comment by soywiz** [comment]
It should use fixed updater if not using the parameter with the time. You can compute a multiplier with:

val ratio = it / 16.milliseconds
x += 2 * ratio

Or use fixedUpdater

For example I have a 144hz screen. If not doing so, I would see it something like 2.1x times faster than when using a 60hz screen

**Comment by emign** [comment]
addUpdater is every frame and fixedUpdater 60 times per second?

**Comment by soywiz** [comment]
`addFixedUpdater` allows you to configure times per second. For example:

```
view.addFixedUpdater(16.666666.milliseconds) {
}
```

after the new version you will also be able to do too:

```
view.addFixedUpdater(60.timesPerSecond) {
}
```

**Comment by emign** [comment]
Nice. We need a video for that

**Comment by soywiz** [comment]
Indeed

**Pull request closed without merging**
