### PR TITLE
Add a 2d collision sample with tile maps.

### PR DESCRIPTION
**Pull request by tsaulic**
A simple example on how to get the camera follow the player traversing a 2d tile map - unable to go past objects in the `collision` layer.

Tested with different tile sizes, as it's dynamic, just change the tile size in the `Config`.

Feel  free to post suggestions on how this can be improved, I'm sure there's many ways, I just lack the knowledge :D

### CODE REVIEW

**Comment by soywiz** [comment]
Really cool sample :)

Are tiles going to be walkable & non-walkable only? Do you plan to support moving half-way into a tile? Or the roguelike is going to be ful-tile movements?

**Comment by tsaulic** [comment]
For now it will be full tile movements, but I do plan to make some colliding tiles into non-colliding tiles so the player can be teleported into walls by some spells (same for monsters) and they start to take damage after some turns if the are unable to move out of it.

**Comment by soywiz** [comment]
Nice! I was wondering if the collision detection could be done by tile: instead of checking coordinates, just check if the tile tile is blocking or no.
The demo looks nice already, so let's merge it and feel free to make PRs improving it if you feel like it :)

**Comment by tsaulic** [comment]
> Nice! I was wondering if the collision detection could be done by tile: instead of checking coordinates, just check if the tile tile is blocking or no. The demo looks nice already, so let's merge it and feel free to make PRs improving it if you feel like it :)

You're right. I'm also working on storing a tiled map state now with coordinates as in (0,0) (0,1) etc. instead of pixel coordinates and storing everything that's in there originally, per layer. Something like that SquidLib does. Hopefully I can get it polished and working soon. I will update if I get it working :D
I think it will be beneficial in the future or path finding, too.

**Pull request merged**
